name: Build package

on: [push]

jobs:
  build-app:

    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2
      - name: Build with Maven
        env:
          spring_profiles_active: dev
        run:
          mvn clean package

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_KEY }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: user/app:latest
